version: '3.8'

services:
  auth-server:
    build:
      context: ./mock/FluVirus.AntiBruteForce.Mock.AuthServer
      args:
        TARGETARCH: x64
    ports:
      - "8080:80"
    env_file:
      - ./env/auth-server/.env
    networks:
      - antibruteforce-network
    depends_on:
      - abfserver
    restart: unless-stopped

  client:
    build:
      context: ./mock/FluVirus.AntiBruteForce.Mock.Client
      args:
        TARGETARCH: x64
    env_file:
      - ./env/client/.env
    networks:
      - antibruteforce-network
    depends_on:
      - auth-server
    restart: unless-stopped

  abfserver:
    build:
      context: ./src/abfserver
    ports:
      - "8081:80"
    env_file:
      - ./env/abfserver/.env
    networks:
      - antibruteforce-network
    restart: unless-stopped

networks:
  antibruteforce-network:
    driver: bridge
